app3/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from app3 import views
from app3.views import Ingrediant_image_view, success, display_ingrediant_images

# TEMPLATE TAGGING
app_name = 'app_3'

urlpatterns=[
    path('image_upload/', Ingrediant_image_view, name = 'image_upload'),
    path('success/', success, name = 'success'),
    path('hotel_images/', display_ingrediant_images, name = 'hotel_images'),
    path('other/',views.Ingrediant_image_view,name='other'),
    path('relative/',views.relative,name='relative'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

prothree/urls.py
from django.contrib import admin
from django.urls import path, include
from app3 import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #takes any request to the home domain, goes to views, returns Index view
    path('', views.index, name='index'),
    # if a request for hompage /app3. go to app3 url.py for following
    path('app3/', include('app3.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app3/models.py
from django.db import models
from django.utils import timezone
from django.forms import ModelForm

# Create your models here.
class Ingrediant(models.Model):
        FRUIT = 'FR'
        VEGETABLE = 'VEGT'
        CARBOHYDRATE = 'CARBS'
        PROTEIN = 'PROT'
        DAIRY = 'DARY'
        FATS = 'FT'
        OILS = 'OL'
        FOOD_GROUPS = (
        (FRUIT, 'Fruits'),
        (VEGETABLE, 'Vegetable'),
        (CARBOHYDRATE, 'Carbohydrate'),
        (PROTEIN, 'Protein'),
        (DAIRY, 'Dairy'),
        (FATS, 'Fats'),
        (OILS, 'Oils'),
    )

        VEGAN = 'VE'
        VEGETARIAN = 'VTRN'
        HALAL = 'HLL'
        KOSHER = 'KSH'
        PESCATARIAN = 'PSC'
        DIETARY_GROUPS = (
        (VEGAN, 'Vegan'),
        (VEGETARIAN, 'Vegetarian'),
        (HALAL, 'Halal'),
        (KOSHER, 'Kosher'),
        (PESCATARIAN, 'Pescatarian'),
    )
        ing_name = models.CharField(max_length=64,unique=True)
        ing_description = models.CharField(max_length=64,null=True)
        ing_price = models.DecimalField(max_digits=5, decimal_places=2)
        ing_weight = models.DecimalField(max_digits=5, decimal_places=2)
        ing_photo = models.ImageField(upload_to='images/', max_length=254, null=True)
        ing_foodgroup = models.CharField(max_length=64,choices=FOOD_GROUPS)
        ing_dietarygroup = models.CharField(max_length=64,choices=DIETARY_GROUPS)
        published_date = models.DateTimeField(blank=True, null=True)


        def publish(self):
            self.published_date = timezone.now()
            self.save()

        def __str__(self):
            return self.ing_photo,self.ing_photo

app3/forms.py
from django import forms
from app3.models import Ingrediant

class IngrediantForm(forms.ModelForm):

    class Meta:
        model = Ingrediant
        fields = ['ing_name',
                    'ing_description',
                    'ing_price',
                    'ing_photo',
                    'ing_weight',
                    'ing_foodgroup',
                    'ing_dietarygroup',
                    'published_date']

app3/views.py
from django.shortcuts import render, redirect
from app3.models import Ingrediant
from django.http import HttpResponse
from app3.forms import IngrediantForm
from app3.models import Ingrediant

# Create your views here.
def index(request):
    ing_list = Ingrediant.objects.order_by('ing_name')
    ing_dict = {'raw_ing':ing_list}
    return render(request,'app3/index.html', context=ing_dict)

#def other(request):
    #return render(request,'app3/other.html')

def relative(request):
    return render(request,'app3/relative_url_templates.html')



def Ingrediant_image_view(request):

    if request.method == 'POST':
        form = IngrediantForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('/app3/success')
    else:
        form = IngrediantForm()
    return render(request, 'app3/ingrediant_image_form.html', {'form' : form})


def success(request):
    return HttpResponse('successfully uploaded')
    
#this view is where we return thr ingrediant to the page.
def display_ingrediant_images(request):

    if request.method == 'GET':

        # getting all the objects of Ingrediant.
        ing = Ingrediant.objects.all()
        return render(request, 'app3/display_inge_images.html',
                     {'actual_images' : ing})

templates/app3/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

templates/app3/display_inge_images.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Detail Img</title>
  </head>
  <body>
    {% if actual_images %}
    <table>
      <thead>

        <th>Ingrediant Name</th>
        <th>Ingrediant Img</th>
      </thead>

    {% for pic in actual_images %}

    <tr>
      <td>  {{ pic.ing_name }} </td>
      <td>  <img src="{{ pic.ing_photo.url }} "></td>
    </tr>

    {% endfor %}

    {% else %}
    <p> NO ING Found</p>
    {% endif %}

    </table>



  </body>


</html>

templates/app3/index.html
{% extends "app3/base.html" %}
{% load static %}

    {% block body_block%}

    <h1>Hello and welcome to the List of Ingrediants!</h1>

    {% if raw_ing %}
    <table>
      <thead>
        <th>Ingrediant Name</th>
        <th>Ingrediant Image</th>
      </thead>

      {% for rawfood in raw_ing %}
      <tr>
        <td>{{ rawfood.ing_name }}</td>
        <td>{{ rawfood.ing_photo }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p> NO ING Found</p>
    {% endif %}

    {% endblock %}

templates/app3/ingrediant_image_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Ing Image Form</title>
  </head>
  <body>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form> 

  </body>
</html>

templates/app3/other.html
<!DOCTYPE html>
{% extends "app3/base.html" %}
    {% block body_block %}
    <h1>This is an example of template inheritance!</h1>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    
    <h2>Officially this is the other.html page!</h2>
    {% endblock %}

templates/app3/relative_url_templates.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <p>
      This page serves as an example of how to
      use relative urls with templates!
      This is the relative_url_templates.html file.
    </p>

    {# Here are the examples:#}
    {# Must set the app_name=basic_app variable inside the basic_app/urls.py#}
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <a href="{% url 'app_3:other' %}">Link to other.html</a>


  </body>
</html>